# 应用名称
spring:
  application:
    name: comomn-gateway
  cloud:
    gateway:
      routes:
        - id: test_router
          uri: https://baidu.com
          predicates:
            - Query=url,qq


server:
  port: 80


